version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    environment:
      AWS_ACCESS_KEY_ID: "AKIASUAVE3N7O6VLAXNR"
      AWS_SECRET_ACCESS_KEY: "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"
      
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
