version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    environment:
      AWS_ACCESS_KEY_ID: "AKIASUAVE3N7O6VLAXNR"
      AWS_SECRET_ACCESS_KEY: "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"
      
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - run:
          name: Login to Docker Hub
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 180432984958.dkr.ecr.us-east-2.amazonaws.com/devopsfe
      - run:
          name: Build Docker Image
          command: |
            docker build -t 180432984958.dkr.ecr.us-east-2.amazonaws.com/devopsfe:latest .
      - run:
          name: Push Docker Image to ECR
          command: |
            docker push 180432984958.dkr.ecr.us-east-2.amazonaws.com/devopsfe:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
